import React from "react";

import ThemeProvider from "@/components/ThemeProvider";
import { useParallaxScroll } from "../hooks/useParallaxScroll";
import TextStrip from "../components/text-strip/TextStrip";
import { whitePaperContent } from "../content/white-paper-content";

const Spacer = ({ height }: { height: string }) => <div style={{ height }} />;

function TheWhitePaper() {
  const offsetY = useParallaxScroll();
  const parallaxFactor = 0.3;

  return (
    <ThemeProvider defaultTheme="dark" storageKey="vite-ui-theme">
      <div className="relative h-auto overflow-x-hidden">
        {/* BACKGROUND LAYER */}
        <div
          className="fixed top-0 left-0 w-full h-[150vh] bg-cover bg-center -z-10"
          style={{
            backgroundImage: `url('/phoenix.jpg')`,
            transform: `translateY(-${offsetY * parallaxFactor}px)`,
          }}
        />

        {/* FOREGROUND CONTENT LAYER */}
        <div className="relative z-10">
          {/* 2. Content is now dynamically generated by mapping over the data array. */}
          <Spacer height="3vh" />

          {whitePaperContent.map((section, index) => (
          // React Fragment is used to provide a key for each item in the loop.
          <React.Fragment key={section.title}>
            <TextStrip title={section.title}>
              {section.content}
            </TextStrip>

            {/* Don't add a spacer after the very last text strip */}
            {index < whitePaperContent.length - 1 && <Spacer height="7vh" />}
          </React.Fragment>
        ))}
        </div>
      </div>
    </ThemeProvider>
  );
}

export default TheWhitePaper;
